language: python
python:
  - "3.5"
  - "3.6"
install:
  # Build/test dependencies
  - pip install -r requirements.txt
  # Get fab to test fab
  - pip install -e .
before_script:
  # Allow us to SSH passwordless to localhost
  - echo "before test"
script:
  # Base tests
  - MyRuns --help
  - MyRuns --version
notifications:
  irc:
    channels: "irc.freenode.org#fabric"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: always
    on_failure: always
  email:
    recipients:
        - ssmarkin@yandex.ru
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
    on_success: always
    on_failure: always